"""Deterministic generator for sql/02_seed.sql.

Produces realistic-but-fixed seed data (fixed RNG seed) that makes every example
scenario in the spec answerable:
  * 12 months of COLLECTIONS + REVENUE per branch (Aug-2025 .. Jul-2026),
  * a deliberate June-2026 revenue dip in a couple of branches (scenario 3),
  * Kerala branches (scenario 4), Chennai vs Bangalore (scenario 2),
  * EMPLOYEE_PERFORMANCE for Q1 & Q2 FY2026 (scenario 5).

Run:  python scripts/gen_seed.py  > sql/02_seed.sql
All identifiers stay UPPERCASE to match 01_schema.sql.
"""
from __future__ import annotations

import random
from datetime import date, timedelta

random.seed(42)

REGIONS = [
    (1, "SOUTH"),
    (2, "NORTH"),
    (3, "EAST"),
    (4, "WEST"),
]

# (id, name, region_id, state, city, growth_bias)
BRANCHES = [
    (1, "Chennai Central", 1, "Tamil Nadu", "Chennai", 1.18),
    (2, "Bangalore Whitefield", 1, "Karnataka", "Bangalore", 0.94),
    (3, "Kochi Marine Drive", 1, "Kerala", "Kochi", 1.05),
    (4, "Trivandrum City", 1, "Kerala", "Trivandrum", 1.02),
    (5, "Hyderabad Hitec", 1, "Telangana", "Hyderabad", 1.08),
    (6, "Mumbai Andheri", 4, "Maharashtra", "Mumbai", 1.10),
    (7, "Delhi Connaught", 2, "Delhi", "New Delhi", 0.98),
    (8, "Kolkata Salt Lake", 3, "West Bengal", "Kolkata", 0.90),
]

PRODUCTS = [
    (1, "Term Insurance Plus", "INSURANCE", 12000.00),
    (2, "Health Shield Gold", "INSURANCE", 18000.00),
    (3, "Motor Secure", "INSURANCE", 9000.00),
    (4, "Wealth Builder ULIP", "INVESTMENT", 25000.00),
    (5, "Fixed Deposit Prime", "INVESTMENT", 50000.00),
    (6, "Home Loan Assist", "LENDING", 30000.00),
]

DEPARTMENTS = ["SALES", "COLLECTIONS", "FINANCE", "OPERATIONS"]
DESIGNATIONS = ["EXECUTIVE", "SENIOR_EXECUTIVE", "MANAGER", "TEAM_LEAD"]

MONTHS = []  # ('YYYY-MM', date_of_first)
_y, _m = 2025, 8
for _ in range(12):
    MONTHS.append((f"{_y:04d}-{_m:02d}", date(_y, _m, 15)))
    _m += 1
    if _m > 12:
        _m = 1
        _y += 1


def esc(s: str) -> str:
    return s.replace("'", "''")


def emit(lines: list[str]) -> None:
    print("\n".join(lines))


print("-- Auto-generated by scripts/gen_seed.py — deterministic seed data.")
print("-- All table/column identifiers UPPERCASE. Load AFTER 01_schema.sql.")
print("USE ENTERPRISE_BI;")
print("SET FOREIGN_KEY_CHECKS = 0;")
print("SET NAMES utf8mb4;")

# ROLES
print("\n-- ROLES")
roles = [
    (1, "BUSINESS_ANALYST", "Read business metrics, build reports"),
    (2, "MANAGER", "Branch and regional oversight"),
    (3, "FINANCE", "Finance, claims, payments, revenue"),
    (4, "SALES", "Sales and collections"),
    (5, "ADMIN", "Full access"),
]
vals = ",\n".join(
    f"({r[0]},'{r[1]}','{esc(r[2])}')" for r in roles
)
print(f"INSERT INTO ROLES (ROLE_ID,ROLE_NAME,DESCRIPTION) VALUES\n{vals};")

# USERS (password_hash is a placeholder bcrypt-shaped string; auth is JWT anyway)
print("\n-- USERS")
users = [
    (1, "analyst", "analyst@abccorp.example", 1),
    (2, "manager", "manager@abccorp.example", 2),
    (3, "finance", "finance@abccorp.example", 3),
    (4, "sales", "sales@abccorp.example", 4),
    (5, "admin", "admin@abccorp.example", 5),
]
ph = "$2b$12$abcdefghijklmnopqrstuvREPLACEWITHREALHASHxxxxxxxxxxxxxx"
vals = ",\n".join(
    f"({u[0]},'{u[1]}','{u[2]}',{u[3]},'{ph}',1)" for u in users
)
print(f"INSERT INTO USERS (USER_ID,USERNAME,EMAIL,ROLE_ID,PASSWORD_HASH,IS_ACTIVE) VALUES\n{vals};")

# REGIONS
print("\n-- REGIONS")
vals = ",\n".join(f"({r[0]},'{r[1]}','India')" for r in REGIONS)
print(f"INSERT INTO REGIONS (REGION_ID,REGION_NAME,COUNTRY) VALUES\n{vals};")

# BRANCHES
print("\n-- BRANCHES")
vals = ",\n".join(
    f"({b[0]},'{esc(b[1])}',{b[2]},'{esc(b[3])}','{esc(b[4])}','2019-01-10',1)"
    for b in BRANCHES
)
print(
    "INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME,REGION_ID,STATE,CITY,OPENED_DATE,IS_ACTIVE) VALUES\n"
    f"{vals};"
)

# PRODUCTS
print("\n-- PRODUCTS")
vals = ",\n".join(
    f"({p[0]},'{esc(p[1])}','{p[2]}',{p[3]:.2f},1)" for p in PRODUCTS
)
print(f"INSERT INTO PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,UNIT_PRICE,IS_ACTIVE) VALUES\n{vals};")

# CUSTOMERS (12 per branch → 96 total; keeps every fact table under the 500 cap)
CUSTOMERS_PER_BRANCH = 12
COLLECTION_CUSTOMERS_PER_BRANCH = 5  # subset used for monthly collections (→ ~480 rows)
print("\n-- CUSTOMERS")
cust_rows = []
cid = 0
customer_by_branch: dict[int, list[int]] = {}
segments = ["RETAIL", "CORPORATE", "SME"]
for b in BRANCHES:
    customer_by_branch[b[0]] = []
    for j in range(CUSTOMERS_PER_BRANCH):
        cid += 1
        name = f"Customer {cid:03d}"
        seg = segments[(cid + j) % 3]
        cust_rows.append(f"({cid},'{name}','{esc(b[3])}','{esc(b[4])}','{seg}',{b[0]})")
        customer_by_branch[b[0]].append(cid)
print(
    "INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,STATE,CITY,SEGMENT,BRANCH_ID) VALUES\n"
    + ",\n".join(cust_rows)
    + ";"
)

# CUSTOMER_ACCOUNTS (one per customer)
print("\n-- CUSTOMER_ACCOUNTS")
acc_rows = []
for c in range(1, cid + 1):
    limit = random.choice([100000, 200000, 500000])
    out = round(random.uniform(0, limit * 0.6), 2)
    status = "ACTIVE" if random.random() > 0.1 else "SUSPENDED"
    acc_rows.append(f"({c},{c},'{status}',{limit:.2f},{out:.2f},'2021-06-01')")
print(
    "INSERT INTO CUSTOMER_ACCOUNTS (ACCOUNT_ID,CUSTOMER_ID,ACCOUNT_STATUS,CREDIT_LIMIT,OUTSTANDING_BALANCE,OPENED_DATE) VALUES\n"
    + ",\n".join(acc_rows)
    + ";"
)

# EMPLOYEES (8 per branch → 64 total)
EMPLOYEES_PER_BRANCH = 8
print("\n-- EMPLOYEES")
emp_rows = []
eid = 0
emp_by_branch: dict[int, list[int]] = {}
for b in BRANCHES:
    emp_by_branch[b[0]] = []
    for j in range(EMPLOYEES_PER_BRANCH):
        eid += 1
        dep = DEPARTMENTS[j % len(DEPARTMENTS)]
        desig = DESIGNATIONS[j % len(DESIGNATIONS)]
        emp_rows.append(
            f"({eid},'Employee {eid:03d}',{b[0]},'{dep}','{desig}','2021-03-15',1)"
        )
        emp_by_branch[b[0]].append(eid)
print(
    "INSERT INTO EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,BRANCH_ID,DEPARTMENT,DESIGNATION,HIRE_DATE,IS_ACTIVE) VALUES\n"
    + ",\n".join(emp_rows)
    + ";"
)

# EMPLOYEE_PERFORMANCE  Q1 & Q2 FY2026
print("\n-- EMPLOYEE_PERFORMANCE (Q1 & Q2 FY2026)")
perf_rows = []
pid = 0
for e in range(1, eid + 1):
    for q in ("Q1", "Q2"):
        pid += 1
        target = random.choice([500000, 750000, 1000000])
        # Q2 generally higher, some employees decline
        factor = random.uniform(0.7, 1.25) if q == "Q1" else random.uniform(0.75, 1.4)
        achieved = round(target * factor, 2)
        score = round(min(100.0, (achieved / target) * 100.0), 2)
        perf_rows.append(f"({pid},{e},'{q}',2026,{target:.2f},{achieved:.2f},{score:.2f})")
print(
    "INSERT INTO EMPLOYEE_PERFORMANCE (PERFORMANCE_ID,EMPLOYEE_ID,FISCAL_QUARTER,FISCAL_YEAR,SALES_TARGET,SALES_ACHIEVED,PERFORMANCE_SCORE) VALUES\n"
    + ",\n".join(perf_rows)
    + ";"
)

# COLLECTIONS — monthly per (branch, customer) with branch growth bias + June dip
print("\n-- COLLECTIONS (12 months x branches)")
coll_rows = []
colid = 0
modes = ["BANK_TRANSFER", "UPI", "CHEQUE", "CARD"]
for b in BRANCHES:
    base = 800000 * (0.6 + 0.1 * b[0])
    for mi, (ym, d0) in enumerate(MONTHS):
        trend = base * (b[5] ** (mi / 11.0))
        # June 2026 dip for Bangalore(2) and Kolkata(8) — powers scenario 3
        if ym == "2026-06" and b[0] in (2, 8):
            trend *= 0.72
        coll_customers = customer_by_branch[b[0]][:COLLECTION_CUSTOMERS_PER_BRANCH]
        per_cust = trend / len(coll_customers)
        for c in coll_customers:
            colid += 1
            amt = round(per_cust * random.uniform(0.85, 1.15), 2)
            day = random.randint(1, 27)
            cd = date(d0.year, d0.month, day)
            mode = random.choice(modes)
            coll_rows.append(
                f"({colid},{b[0]},{c},'{cd.isoformat()}','{ym}',{amt:.2f},'{mode}')"
            )
# chunk the big insert to keep statements readable
print("INSERT INTO COLLECTIONS (COLLECTION_ID,BRANCH_ID,CUSTOMER_ID,COLLECTION_DATE,COLLECTION_MONTH,COLLECTION_AMOUNT,PAYMENT_MODE) VALUES")
print(",\n".join(coll_rows) + ";")

# REVENUE — monthly per branch (June dip mirrors collections)
print("\n-- REVENUE (12 months x branches)")
rev_rows = []
rid = 0
for b in BRANCHES:
    base = 1200000 * (0.6 + 0.1 * b[0])
    for mi, (ym, _d0) in enumerate(MONTHS):
        amt = base * (b[5] ** (mi / 11.0)) * random.uniform(0.95, 1.05)
        if ym == "2026-06" and b[0] in (2, 8):
            amt *= 0.70
        cost = amt * random.uniform(0.55, 0.7)
        margin = amt - cost
        rid += 1
        rev_rows.append(f"({rid},{b[0]},'{ym}',{amt:.2f},{cost:.2f},{margin:.2f})")
print("INSERT INTO REVENUE (REVENUE_ID,BRANCH_ID,REVENUE_MONTH,REVENUE_AMOUNT,COST_AMOUNT,GROSS_MARGIN) VALUES")
print(",\n".join(rev_rows) + ";")

# SALES — a few per branch across months
print("\n-- SALES")
sale_rows = []
sid = 0
SALES_PER_BRANCH = 60  # 8 branches → 480 rows
for b in BRANCHES:
    for _ in range(SALES_PER_BRANCH):
        sid += 1
        p = random.choice(PRODUCTS)
        qty = random.randint(1, 5)
        emp = random.choice(emp_by_branch[b[0]])
        cust = random.choice(customer_by_branch[b[0]])
        ym, d0 = random.choice(MONTHS)
        sd = date(d0.year, d0.month, random.randint(1, 27))
        amt = round(p[3] * qty, 2)
        sale_rows.append(
            f"({sid},{b[0]},{p[0]},{emp},{cust},'{sd.isoformat()}',{qty},{p[3]:.2f},{amt:.2f})"
        )
print(
    "INSERT INTO SALES (SALE_ID,BRANCH_ID,PRODUCT_ID,EMPLOYEE_ID,CUSTOMER_ID,SALE_DATE,QUANTITY,UNIT_PRICE,SALE_AMOUNT) VALUES\n"
    + ",\n".join(sale_rows)
    + ";"
)

# CLAIMS + PAYMENTS
print("\n-- CLAIMS")
claim_rows = []
pay_rows = []
clid = 0
payid = 0
statuses = ["SUBMITTED", "APPROVED", "DENIED", "PAID"]
CLAIMS_PER_BRANCH = 30  # 8 branches → 240 claims (PAYMENTS derived from PAID/APPROVED)
for b in BRANCHES:
    for _ in range(CLAIMS_PER_BRANCH):
        clid += 1
        cust = random.choice(customer_by_branch[b[0]])
        ym, d0 = random.choice(MONTHS)
        cdt = date(d0.year, d0.month, random.randint(1, 27))
        amt = round(random.uniform(5000, 80000), 2)
        st = random.choice(statuses)
        settled = amt if st == "PAID" else (round(amt * random.uniform(0.4, 0.9), 2) if st == "APPROVED" else 0.0)
        claim_rows.append(f"({clid},{cust},{b[0]},'{cdt.isoformat()}',{amt:.2f},'{st}',{settled:.2f})")
        if st in ("PAID", "APPROVED"):
            payid += 1
            pd = cdt + timedelta(days=20)
            pay_rows.append(
                f"({payid},{clid},{cust},{b[0]},'{pd.isoformat()}',{settled:.2f},'BANK_TRANSFER')"
            )
print(
    "INSERT INTO CLAIMS (CLAIM_ID,CUSTOMER_ID,BRANCH_ID,CLAIM_DATE,CLAIM_AMOUNT,CLAIM_STATUS,SETTLED_AMOUNT) VALUES\n"
    + ",\n".join(claim_rows)
    + ";"
)
print("\n-- PAYMENTS")
print(
    "INSERT INTO PAYMENTS (PAYMENT_ID,CLAIM_ID,CUSTOMER_ID,BRANCH_ID,PAYMENT_DATE,PAYMENT_AMOUNT,PAYMENT_MODE) VALUES\n"
    + ",\n".join(pay_rows)
    + ";"
)

# INVENTORY (one per branch/product subset)
print("\n-- INVENTORY")
inv_rows = []
invid = 0
for b in BRANCHES:
    for p in PRODUCTS[:4]:
        invid += 1
        qoh = random.randint(0, 500)
        reorder = 50
        inv_rows.append(f"({invid},{b[0]},{p[0]},{qoh},{reorder},'2026-06-30')")
print(
    "INSERT INTO INVENTORY (INVENTORY_ID,BRANCH_ID,PRODUCT_ID,QUANTITY_ON_HAND,REORDER_LEVEL,LAST_RESTOCK_DATE) VALUES\n"
    + ",\n".join(inv_rows)
    + ";"
)

# PROCUREMENT
print("\n-- PROCUREMENT")
proc_rows = []
poid = 0
suppliers = ["Acme Supplies", "Global Traders", "Prime Vendors", "Metro Wholesale"]
PROCUREMENT_PER_BRANCH = 10  # 8 branches → 80 purchase orders
for b in BRANCHES:
    for _ in range(PROCUREMENT_PER_BRANCH):
        poid += 1
        p = random.choice(PRODUCTS)
        qty = random.randint(50, 400)
        amt = round(p[3] * qty * 0.6, 2)
        ym, d0 = random.choice(MONTHS)
        od = date(d0.year, d0.month, random.randint(1, 27))
        st = random.choice(["OPEN", "RECEIVED", "CANCELLED"])
        sup = random.choice(suppliers)
        proc_rows.append(
            f"({poid},{b[0]},{p[0]},'{sup}','{od.isoformat()}',{qty},{amt:.2f},'{st}')"
        )
print(
    "INSERT INTO PROCUREMENT (PURCHASE_ORDER_ID,BRANCH_ID,PRODUCT_ID,SUPPLIER_NAME,ORDER_DATE,QUANTITY_ORDERED,ORDER_AMOUNT,ORDER_STATUS) VALUES\n"
    + ",\n".join(proc_rows)
    + ";"
)

print("\nSET FOREIGN_KEY_CHECKS = 1;")
print("-- End of seed.")
